### ISSUE TITLE
support fastly

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/npm-register#17]
fastly might be able to provide more granular caching to make elephant faster. Potentially this could also allow us to CDN private packages.

**Comment by Ianfeather** [comment]
Looking at this one because we use fastly and will probably look to add it in at some point. What's the scope of this task?

- Update invalidate.js to work for multiple CDN providers? When is this file run btw?
- Abstract out mentions of cloudfront in the codebase and build in configuration for different CDN providers?
- More granular caching. Is this still a goal? Could you give more detail about what you mean and how fastly would be able to help?

**Comment by dgautsch** [comment]
@Ianfeather is this still a feature you'd like to see supported?

**Comment by Ianfeather** [comment]
After revisiting, i'm not 100% sure what the goal of the original issue was tbh.

We use fastly in front on npm-register although we didn't need any extra features to do this. We don't invalidate via npm-register though which might be the difference
